typedef struct card* Card;
typedef struct deck* Deck;
typedef struct pilha* Pilha;

Card newCard();
Card setCardpos(Card, int);
Card getCa(Deck, int);
Card grCa(Deck, int);
Card getPilha(Pilha, int);
Deck newDeck();
Pilha newPilha();
int checkNum(char, int[], int);
int checkChar(char, char[], int);
int getCnum(Card);
int getCpos(Card);
int getCvc(Card);
int getCvn(Card);
char getCc(Card);
void setAllVisCC(Card);
void setAllVisNC(Card);
void DeckNull(Deck, int);
void shuffleDeck(Card*, int);
void createDeck(Deck);
void ConsCard(int, Card, char, int);
void giveTipN(Card*, int);
void giveTipC(Card*, char);
void printCards(Deck);
void swapT(Card *, Card *);
int partitionT(Card *, int , int );
void sortTrash(Deck , int , int );
void sortPilha(Pilha , int , int );
void gototrash(Deck, Card, int);
void freePi(Pilha);